### ISSUE TITLE
Repository Not Found

### ISSUE THREAD

**Issue by TavernerResearch** [TrustedLLM/LLMDet#9]
Hello,

Giving this a trial today and I had similar install issues as noted here:
https://github.com/TrustedLLM/LLMDet/issues/5
So not sure if the fix put in place has been walked back at some stage (I worked around it by adding the ignore flag to my environment).

But when it comes to running the example script (popped in to a file called test.py) I'm hitting an issue that it's trying to access a huggingface repository that no longer seems to exist (I copy and pasted it to the browser and get a similar error):

> D:\>python test.py
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.08it/s]
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 88.88it/s]
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 33.85it/s]
> Traceback (most recent call last):
>   File "\Python\Python312\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
>     response.raise_for_status()
>   File "\Python\Python312\site-packages\requests\models.py", line 1021, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/decapoda-research/llama-7b-hf/resolve/main/tokenizer_config.json
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "\Python\Python312\site-packages\transformers\utils\hub.py", line 398, in cached_file
>     resolved_file = hf_hub_download(
>                     ^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1403, in hf_hub_download
>     raise head_call_error
>   File "\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1261, in hf_hub_download
>     metadata = get_hf_file_metadata(
>                ^^^^^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\huggingface_hub\file_download.py", line 1674, in get_hf_file_metadata
>     r = _request_wrapper(
>         ^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\huggingface_hub\file_download.py", line 369, in _request_wrapper
>     response = _request_wrapper(
>                ^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\huggingface_hub\file_download.py", line 393, in _request_wrapper
>     hf_raise_for_status(response)
>   File "\Python\Python312\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
>     raise RepositoryNotFoundError(message, response) from e
> huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6621cb81-1d42eb2310a93423525ea0ba;c188e640-b1b0-49b9-af35-9cde134d188b)
> 
> Repository Not Found for url: https://huggingface.co/decapoda-research/llama-7b-hf/resolve/main/tokenizer_config.json.
> Please make sure you specified the correct `repo_id` and `repo_type`.
> If you are trying to access a private or gated repo, make sure you are authenticated.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\", line 8, in <module>
>     result = llmdet.detect(text)
>              ^^^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\llmdet\detector.py", line 118, in detect
>     tokenizer = LlamaTokenizer.from_pretrained(model["model_name"])
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\transformers\tokenization_utils_base.py", line 2010, in from_pretrained
>     resolved_config_file = cached_file(
>                            ^^^^^^^^^^^^
>   File "\Python\Python312\site-packages\transformers\utils\hub.py", line 421, in cached_file
>     raise EnvironmentError(
> OSError: decapoda-research/llama-7b-hf is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
> If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Contents of test.py:
```
import llmdet

llmdet.load_probability()

text = "The actress was honoured for her role in 'The Reader' at the annual ceremony, which was held at the Royal Albert Hall. The film, which is based on the novel by the same name by Philip Roth, tells the story of a New York Times reporter who returns to his hometown to cover the death of his brother-in-law. Winslet plays his wife, with whom he has been divided since the death of their son.\nIn the film, Winslet plays the mother of the grieving brother-in-law.\nThe actress also won a Golden Globe for her role in the film at the ceremony in November.\nWinslet was also nominated for an Oscar for her role in 'The Reader'.\nThe 63-year-old Winslet was seen accepting her awards at the ceremony, where she was joined by her husband, John Krasinski, who has been nominated for best supporting actor in the film.\nWinslet and Krasinski met while"

# Detect, `text` is a string or string list
result = llmdet.detect(text)
print(result)
```

So at this point I'm out my comfort zone and not sure how to resolve?

**Comment by TavernerResearch** [comment]
Ah, so, got a bit further:

> \site-packages\llmdet\detector.py

Commented out line 100:
`{"model_name": "decapoda-research/llama-7b-hf", "vocab_size": 32000, "model_probability": "llama"},`
and this got me a bit further:
`[LightGBM] [Fatal] The number of features in data (10) is not the same as it was in training data (11).`
Which I guess is somewhat to be expected, as I've removed a set, there is a:
`You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.`
clue of what to do next, I just gotta work out how to do that = p

**Comment by cansee5** [comment]
This is a timeliness error. Now the model address of "decapoda-research/llama-7b-hf" no longer exists. You can replace "decapoda-research/llama-7b-hf" with "baffo32/decapoda-research-llama-7B-hf". - hf. At the same time, I also updated the code on Github, you can try it again.

**Comment by TavernerResearch** [comment]
Yep, that's got it working - thank you!
